#!/bin/bash 
# /etc/init.d/wvdial

### BEGIN INIT INFO
# Provides:          TheInternet
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here
KDIR=/var/log/kinisiinternet
KSCR=/usr/local/kinisi-agent-nodejs/scripts

mkdir -p "${KDIR}" || true

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting GPRS Internet"
    devglob="/dev/serial/by-id/usb-*-if00-port0"
    echo > "${KDIR}/log.out"
    while [ ! -e $devglob ] ; do
       echo "starting device" >> "${KDIR}/log.out"

       lsusb | grep "12d1:14d1" -q
       if [ $? -eq 0 ] ; then
         usb_modeswitch -c ${KSCR}/12d1\:14d1
         echo "found 12d1:14d1" >> "${KDIR}/log.out"
       fi

       lsusb | grep "12d1:14fe" -q
       if [ $? -eq 0 ] ; then
         usb_modeswitch -c ${KSCR}/12d1\:14fe
         echo "found 12d1:14fe" >> "${KDIR}/log.out"
       fi

       sleep 5
    done
    dev=$(ls -1 $devglob)
    echo -e "AT+CPIN=1111\r" > "$dev"
    while read line ; do 
       echo "line: [$line]" >> "${KDIR}/log.out"
       if [[ $line == OK* ]] ; then
	  echo "Pin entered successfully" >> "${KDIR}/log.out"
	  break
       elif [[ $line == *ERROR* ]] ; then
	  echo "Pin error detected" >> "${KDIR}/log.out"
	  break 
       else
	  echo "Unknown line [$line]" >> "${KDIR}/log.out"
       fi
    done < "$dev"
    WVPROFILE=""
    ICCID=$("${KSCR}/get_iccid.sh" "$dev")
    if [[ $ICCID == 89320300* ]] ; then
      WVPROFILE="base"
    else
      WVPROFILE="tmobile"
    fi
    # wvdial needs /dev/kinisimodem
    ln -sf "$dev" /dev/kinisimodem
    # run application you want to start
    /sbin/start-stop-daemon --start --background --quiet --no-close --retry forever/1 --pidfile "${KDIR}/wvdial.pid" --make-pidfile --exec /usr/bin/wvdial "${WVPROFILE}" > "${KDIR}/wvdial.stdout" 2> "${KDIR}/wvdial.stderr"
    ;;
  stop)
    echo "Stopping GPRS Internet"
    # kill application you want to stop
    /sbin/start-stop-daemon --stop --pidfile "${KDIR}/wvdial.pid" --exec /usr/bin/wvdial
    rm -f "${KDIR}/wvdial.pid"
    ;;
  *)
    echo "Usage: /etc/init.d/kinisiinternet {start|stop}"
    exit 1
    ;;
esac

exit 0
