#!/bin/bash
### BEGIN INIT INFO
# Provides:          kinisiagent
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Kinisi Agent
# Description:       Kinisi Agent written in Node.JS
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export NODE_ENV=${NODE_ENV:-"production"}

FOREVER=/usr/local/bin/forever
HOME=/root

LOGDIR=/var/log/kinisiagent
SRCDIR=/usr/local/kinisi-agent-nodejs
PIDFILE=/var/run/kinisiagent.pid
FUID=kinisiagent

if [ ! -d $LOGDIR ]; then
	mkdir -p $LOGDIR
fi

case "$1" in
  start)
    pushd $SRCDIR
    $FOREVER start -p $SRCDIR --uid "$FUID" --sourceDir $SRCDIR --pidFile $PIDFILE -a -o $LOGDIR/out.log -l $LOGDIR/forever.log -e $LOGDIR/err.log --minUptime 1000 --spinSleepTime 1000 kinisi-agent.js
    popd
    ;;
  stop)
    if [ -e $PIDFILE ]; then 
      $FOREVER stop $FUID
    fi
    ;;
  restart)
    if [ -e $PIDFILE ]; then 
      $FOREVER restart $FUID
    else
      echo "kinisi agent pid file not found, consider calling start"
      exit 1
    fi
    ;;
  status)
    if [ -e $PIDFILE ]; then
      ps up $(cat $PIDFILE)
    else
      echo "kinisi agent pid file not found"
    fi 
    ;;
  *)
    echo "Usage: /etc/init.d/kinisiagent {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
